lbl-anp/becquerel

- .gitignore
Pytest recently started creating hidden files that are not covered by the current gitignore, so I updated the whole file using github/gitignore/Python.gitignore
> Update gitignore from github/gitignore

- becquerel/tools/nndc.py
- tests/nndc_test.py
Minor update to NNDC query API that is transparent to the user, plus added more checks to the NNDC tests. Affects both `fetch_wallet_card` and `fetch_decay_radiation`.
Fixes #96
> Fix #96 (NNDC kwargs conflict)

- becquerel/core/energycal.py
- tests/energycal_test.py
Fixes issue #117.
`from_point` does execute the function `update_fit()` internally. Furthermore, there is a flag to include the origin/(0,0) into the fit, without adding it to the list. I also added a manual linear regression to the tests, to check if the coefficients are calculated correctly.
> Bugfix energycal

- tests/samples/INVENTORY.md
Add information table for example spectrum files
Related to the table originally created in #93
> Add example spectrum inventory table

- becquerel/tools/__init__.py
- examples/isotopes.ipynb
- examples/nndc_chart_of_nuclides.ipynb
- examples/nndc_examples.ipynb
- examples/xcom_examples.ipynb
> Clean up tool imports

- becquerel/parsers/spe_file.py
- becquerel/parsers/spectrum_file.py
- tests/autocal_test.py
- tests/parsers_test.py
> Read SPE PRESETS as metadata

- becquerel/tools/materials.py
> Make parsing of NIST element data more robust

- becquerel/core/spectrum.py
- examples/spectrum.ipynb
- tests/spectrum_test.py
Fixes #198, including updated documentation, tests, and notebooks.
> let find_bin_index find indices for multiple x values

- becquerel/core/spectrum.py
> add get_bin_info and change default: find_bin_index(use_kev=None)

- becquerel/tools/isotope.py
Useful for converting mass of material to activity
> add specific_activity prop to bq.Isotope

- becquerel/core/fitting.py
> improve peak amplitude guess for gauss, gausserf, expgauss

- .github/workflows/coveralls.yaml
- .github/workflows/tests.yaml
> Run actions on schedule (nightly) and manually

- .github/workflows/pypi.yaml
The title says it all 😄 but this will need to be tested.
> Automatically deploy to pypi on new version tags

- .github/workflows/pypi.yaml
- .github/workflows/tests.yaml
> Add python 3.9 to CI

- .bumpversion.cfg
- .github/workflows/pypi.yaml
- becquerel/__metadata__.py
> Version 0.4.4 with pypi CD tag fix

- becquerel/tools/nndc.py
NNDC updated from nudat2 to nudat3. Old requests seem to be failing, I think this may fix it.
> Update nudat2 to nudat3

- becquerel/core/fitting.py
Closes https://github.com/lbl-anp/becquerel/issues/305.
@jvavrek Check this out if it works for you. If you have a good test for this, based on the case where you run into this, it would probably be a good idea to add this.
> Fix ErfModel

- .pre-commit-config.yaml
- requirements.txt
See #328 for (a lot) more details
> Bump black fmt to 22.3.0 to fix issues with click

- becquerel/core/fitting.py
> Fix numpy complex dtype deprecation warning

- .github/workflows/tests.yaml
- requirements-dev.txt
…  and assure each file's tests run on the same node.
Closes #336
> Add parallel pytest'ing to the test action

- becquerel/tools/xcom.py
Their API must have changed slightly recently. This PR contains a small fix.
> Update code to pass correct POST requests to XCOM

- becquerel/core/fitting.py
- becquerel/tools/wallet_cache.py
- requirements.txt
- tests/fitting_test.py
Convenience function for fit parameter relative uncertainty
> add Fitter.param_rel_unc and adjust pandas append to concat

- becquerel/__metadata__.py
We have CI for python3.11 as well: https://github.com/lbl-anp/becquerel/commit/ddf3aeb2f3bc29dea2142f63777cf577a3c5f02d
> Update __metadata__.py to include python3.11

- README.md
https://github.com/actions/starter-workflows/issues/1525
> fix test badge in README.md

- becquerel/core/spectrum.py
- becquerel/tools/xcom.py
- tests/spectrum_test.py
Compute what a spectrum would look like after being attenuated by a given areal density of a given material, using the XCOM tools.
> Add Spectrum.attenuate method

- becquerel/core/spectrum.py
- tests/spectrum_test.py
Adds:
```
Spectrum.deadtime
Spectrum.deadtime_fraction
Spectrum.livetime_fraction
```
> add Spectrum properties for live/deadtime-related quantities

- tests/spectrum_test.py
https://github.com/PyCQA/pycodestyle/issues/1201
> fix pre-commit false positives

- becquerel/core/spectrum.py
- tests/spectrum_test.py
> fix Spectrum inheritance

- becquerel/core/fitting.py
- tests/fitting_test.py
I thought there was an existing way to get this, but maybe not?
> add Fitter.param_val_and_unc

- becquerel/core/fitting.py
- tests/fitting_test.py
- add type hints to fit-uncertainties-related things
- ensure that relative uncertainties are non-negative
> Update relative uncertainties and related code

- becquerel/tools/xcom.py
- tests/plotting_test.py
> Revert kludge to work around XCOM issue

- becquerel/core/energycal.py
- becquerel/tools/isotope.py
- becquerel/tools/nndc.py
- becquerel/tools/wallet_cache.py
- requirements.txt
Missed by #242 when closing #182
> Remove remaining "from future" imports

- .github/workflows/coveralls.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/pypi.yaml
- .github/workflows/tests.yaml
- becquerel/__metadata__.py
- pyproject.toml
Various changes in here:
* Remove support for python3.8
* Add support for python3.13
* Update ubuntu to latest
* Update GitHub actions versions
> Update CI settings

- .pre-commit-config.yaml
- becquerel/core/fitting.py
- becquerel/core/plotting.py
- becquerel/core/spectrum.py
- becquerel/core/utils.py
- becquerel/io/__init__.py
- becquerel/io/h5.py
- becquerel/parsers/cnf.py
- becquerel/parsers/spc.py
- becquerel/tools/materials.py
- becquerel/tools/xcom.py
- examples/autocal.ipynb
- pyproject.toml
- tests/fitting_test.py
...and fix minor issues that have arisen.
> Run pre-commit autoupdate

- becquerel/core/spectrum.py
- tests/spectrum_test.py
I noticed some opportunities to add useful spectrum properties and clean up `Spectrum.__str__` in the process.
> Spectrum properties

- becquerel/parsers/cnf.py
Make more clear that we don't have 'proprietary' knowledge of the format.
> Update language describing CNF parser
