lbl-anp/becquerel

becquerel/tools/nndc.py
tests/nndc_test.py

These modifications reduce the time for running the tests from 83 seconds to 41 seconds on my machine, while maintaining the same test coverage.
I am also interested in enabling webtests for Travis CI if this PR and #69 are accepted.

Double the speed of NNDC tests

---

becquerel/tools/xcom.py
requirements.txt

The XCOM web API seems to have changed sometime in the last month. This PR updates the tool so that it works again.
Two notes:
* [`BeautifulSoup4`](https://www.crummy.com/software/BeautifulSoup/) was added as a dependency since it is needed by `pandas` to parse HTML tables. This will also ensure #63 is fixed.
* Four webtests still fail since the Mixture query on [XCOM](https://physics.nist.gov/PhysRefData/Xcom/html/xcom1.html) seems to be broken at this time.

Update XCOM tool to read current web API

---

.travis.yml

Now that we are requiring PRs to branch off of `develop`, we need to add `develop` to the Travis configuration YAML to trigger PR builds.

Add develop branch to travis configuration

---

README.md
becquerel/core/energycal.py
becquerel/core/utils.py
becquerel/tools/isotope.py
becquerel/tools/isotope_qty.py
becquerel/tools/materials.py
becquerel/tools/nndc.py
becquerel/tools/wallet_cache.py
becquerel/tools/xcom.py
requirements-dev.txt
requirements.txt
tests/isotope_qty_test.py

Remove six as a dependency and update dependencies

---

becquerel/__init__.py
becquerel/core/plotting.py
becquerel/core/spectrum.py
becquerel/core/utils.py
setup.cfg
tests/core_test.py

Closes #140 
Closes #122 
Closes #113 
Closes #112 
To do:
Remarks:
* Addition: Only allowed it if both spectrum were initiated identically with `counts` or `cps`, respectively. If this is not the case the user can enforce addition with `Spectrum(counts=specA.counts+specB.counts)` or `Spectrum(cps=specA.cps+specB.cps)` as suggested in the error message.
* Question: Should a warning be raised if `counts` were added and `livetime` have been ignored (because one of them was `None`)?
* Subtraction: If `cps` is available in both subtract `cps` and create a new spectrum with `cps`. If one of the `cps` values has been derived from `counts` and `livetime` it raises a warning. If `cps` is not available in one of the spectra try subtraction of `counts` and set `uncs` to `np.nan`; this always raises …

Spectrum bugfixes

---

setup.cfg

This **patches** two warning which persist during testing:
- py3 `__spec__` issue
- Actual resolution unknown currently, see #150
- A warning from uncertainties using a deprecated call
- Actual resolution in a PR I've submitted: https://github.com/lebigot/uncertainties/pull/88

Ignore pytest warnings

---

tests/core_test.py

We get a ton of the follow warnings during testing with `pytest3.8.*`:
```bash
~/repos/becquerel/tests/core_test.py:470: RemovedInPytest4Warning: Fixture "spec_data" called directly. Fixtures are not meant to be called directly, are created automatically when test functions request them as parameters. See https://docs.pytest.org/en/latest/fixture.html for more information.
spec1, spec2 = (get_spectrum(type1, lt=lt1),
```
This was due to improper usage of pytest fixtures as plain functions. I've updated the Spectrum tests to avoid the need to use the fixtures directly by inverting the order of the called helper functions (not fixtures.) This passes locally on `py27`/`py36`. Let's see if Travis agrees ...

Update/improve Spectrum test fixtures for pytest4 compat

---

LICENSE.txt
MANIFEST.in
README.md
RELEASING.md
setup.py

Closes #164, #165, #166
Hotfix for the following:
- Resolves issue with installing from PyPi in `python2`
- Adds `MANIFEST.in` for non-source text files
- Updates `RELEASING.md` for tagging, testing and uploading instructions
- Bumps MICRO version

Release 0.2.1

---

becquerel/parsers/spe_file.py

A spe file with a blank line after the `$SPEC_REM` tag raises an `IndexError` when trying to get the first value of the line and checking that it isn't a `$`. I've fixed this in two places to use `startswith` instead.

Fix bug when empty line after $SPEC_REM tag in a spe file

---

becquerel/core/spectrum.py
examples/spectrum.ipynb
tests/spectrum_test.py

This splits up a large block of tests I had written previously into several smaller tests focusing separately on list mode and find index functionalities.

Issue tests #200: Spectrum tests and associated changes to bin-related methods and docstrings

---

.travis.yml
requirements.txt

* Update travis to run on Ubuntu Bionic
* Update travis to use python 3.8
* Fix numba and lvmlite versions for python2. See https://github.com/numba/llvmlite/pull/580

Update travis build spec, numba and llvmlite

---

requirements.txt

Fix the issue coming up in Travis with python3 versions:
```
error: llvmlite 0.31.0 is installed but llvmlite<0.34,>=0.33.0.dev0 is required by {'numba'}
```

Update requirements to deal with python2/3 llvmlite issue

---

becquerel/tools/nndc.py
tests/nndc_test.py

It appears that two things have changed on NNDC in recent months:
(1) The error message that is returned when requesting too many wallet cards has changed
(2) The decay mode kwarg no longer seems to be honored in the query
Change (1) was leading to the recent test failures on Travis. Fixing (1) leads to (2) causing a separate test to fail, one that requests all wallet cards for spontaneous fission isotopes (`decay="SF"`), which used to be a small enough number to not matter but now thousands of isotopes are returned. This PR skips that test and raises a warning when specifying the `decay` kwarg.
Other tests whose queries are affected by (2) do not raise errors because they are generally not strict in their testing; they usually check that no error was raised by the query and that a …

Adjust for recent changes to NNDC API

---

.pylintrc
.travis.yml
CONTRIBUTING.md
RELEASING.md

This pull request will fix the internals so that we can rename master to main and remove develop.
Changes on github required to go along with this pull request:
Let me know if I forgot something.

From master to main transition

---

becquerel/tools/isotope_qty.py
tests/isotope_qty_test.py

Closes #222
These changes assure that whatever quantity is used to initalize a `IsotopeQuantity` that quantity will not be affected by floating point rounding errors.

IsotopeQuantity retain floating point precision

---

becquerel/core/fitting.py
becquerel/core/spectrum.py

The `Fitter` class currently lacks a simple `plot` method for displaying just the fit result, especially if one wants to quickly overlay it on an existing plot. This provides such a method.

Add a simple plot() method to Fitter

---

becquerel/core/spectrum.py

I'm opening this since I think we talked about getting #180 soon as well. Is there anything other than simply adding a `self.cal` to `Spectrum`? Perhaps the `rebin` or `combine_bins` change the calibration, depending on how the calibration is defined?
Thoughts @jccurtis @markbandstra @cosama ?

Draft: store EnergyCal object in Spectrum

---

becquerel/core/spectrum.py
tests/energycal_test.py
tests/spectrum_test.py

Fix the auto merge of #229 
> I'm opening this since I think we talked about getting #180 soon as well. Is there anything other than simply adding a self.cal to Spectrum? Perhaps the rebin or combine_bins change the calibration, depending on how the calibration is defined?
> 
> Thoughts @jccurtis @markbandstra @cosama ?

Store EnergyCal in Spectrum

---

becquerel/core/fitting.py

Quick PR to add error bounds from the fit to `custom_plot`, and also ensure that the fit line and error band are drawn above other lines

plot the fit evaluation error bands, and ensure fit is shown above other lines

---

becquerel/core/utils.py
becquerel/tools/isotope_qty.py
tests/isotope_qty_test.py

Let date be a date, not just datetime; also default _at() methods to now()

---

becquerel/core/calibration.py
tests/calibration_test.py

Fit stats for calibrations:
- R^2
- chi^2
- dof
- reduced chi^2

Calibration fit statistics

---

becquerel/core/peakfinder.py
tests/autocal_test.py

update peakfinder to suppress double peaks and update plots

---

becquerel/core/fitting.py
becquerel/core/spectrum.py
becquerel/parsers/cnf_file.py
becquerel/parsers/spc_file.py
becquerel/parsers/spe_file.py
becquerel/parsers/spectrum_file.py
tests/energycal_test.py
tests/fitting_test.py
tests/plotting_test.py
tests/rebin_test.py
tests/spectrum_test.py

Closes #272.
This fixes those to to `float` and `int`.

np.float and np.int are deprecated

---

tests/isotope_test.py

I was double-checking a few things and thought these tests would be useful. As documented, we compare the specific activities returned by `bq.Isotope` against values from an NRC publication where possible. For most of the isomers, this isn't possible, so we just test against bq's current results as a sort of regression test.

Test specific_activity prop against NRC values where possible

---

becquerel/core/utils.py
tests/test_utils.py

Simple util to generate square root bins.

Implement a square root binning function

---

COPYRIGHT.txt
LICENSE.txt
README.md
becquerel/__metadata__.py
requirements-dev.txt
requirements.txt
setup.cfg
tests/metadata_test.py

* Updates copyright and license text
* Removes version number test since this is no longer in the copyright
* Adds `bump2version`
* Bumps version -> `0.4.0`
* Linked to LBNL OSS - 2021-164

2021 copyright and bump2version

---

becquerel/__metadata__.py
setup.cfg

This PR will testing the auto deploy to pypi action. Once we merge this in we can tag `main`

Bump version: 0.4.0 → 0.4.1

---

.bumpversion.cfg
.github/workflows/pypi.yaml
becquerel/__metadata__.py
setup.cfg

* Update pypi workflow to always run (build/check), only upload with a new tag and include the source+wheel
* Move `bump2version` config to its own file to avoid issues with `pre-commit`
* Rolls patch version

Version v0.4.3 with pypi CD improvements and bump2version/pre-commit fix

---

becquerel/core/fitting.py
tests/fitting_test.py

Return 0 error estimate and warn instead of crashing in `Fitter.calc_area_and_unc()`

Downgrade fitting error

---

becquerel/tools/isotope_qty.py
examples/isotopes.ipynb
examples/overview.ipynb

This is a quick one in response to #325

Remove notebook calls to IsotopeQuantity.*_now methods and update docs

---

becquerel/tools/materials_compendium.py
tests/materials_test.py

Enable the latest Compendium materials JSON format to be read

---

becquerel/core/rebin.py
becquerel/core/spectrum.py
tests/rebin_test.py
tests/spectrum_test.py

This PR allows the user to specify whether "overflow" events are included in the leftmost and rightmost bins when rebinning. Changes the default to *not* including overflow events since it can lead to confusion (see #334).
The following MWE demonstrates the different functionality:
```python
import numpy as np
import becquerel as bq
counts = 1000 * np.ones(10)
spec = bq.Spectrum(counts=counts)
cal = bq.Calibration("p[0] * x", [1.0])
spec.apply_calibration(cal)
print("Original spectrum:")
print("edges: ", spec.bin_edges_kev)
print("values:", spec.counts_vals)
for edges in [
np.linspace(2, 9, num=8),
np.linspace(2.5, 9.5, num=8),
]:
for method in ["interpolation", "listmode"]:
for include_overflows in [True, False]:
spec2 = spec.rebin(edges, method=method, …
```

Include or exclude "overflow" events when rebinning

---

becquerel/tools/isotope_qty.py

This will fix the current main failing for `numpy==1.23.X` on ubuntu.
See also: https://github.com/numpy/numpy/issues/22386

changes all np.exp to np.expm1 in istope_qty

---

.github/workflows/tests.yaml

Some of the tests remain flaky, and by default all of the running tests get canceled if there is one failure. This change is an attempt to keep the tests running.

Do not cancel other tests if there is a failure

---

becquerel/core/peakfinder.py

without this changing the min_snr to a higher value did not change the found peaks.

peakfinder: reset found peaks before looking for new peaks. Fixes #352

---

becquerel/tools/nndc.py

As of about two weeks ago, requesting data from .jsp sites (like https://www.nndc.bnl.gov/nudat3/sigma_searchi.jsp) for wallet card and decay data information began returning empty request errors: "NNDCRequestError: Request failed: "
After speaking with a Technology Analyst at Brookhaven, they concluded a few things. sigma_searchi.jsp provides a response object with "ok == True" and "status_code == 200". It's "reason" field is set to an empty string instead of "OK". In line 439, the 'resp.reason != "OK"' condition causes _request() to fail, despite NNDC returning data. Removing this condition fixes it and returns data successfully.

Fix nndc._request()

---

becquerel/tools/materials_nist.py
tests/materials_test.py

This shows that the extra messages are of the form:
```
FAILED tests/materials_test.py::test_materials_dummy_compendium_2022 - AssertionError: Expected no MaterialsWarnings to be raised; got ["Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.", "Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object."]
```

update assert messages in materials_test.py

---

becquerel/tools/xcom.py

This change removes the following warning that occurs when querying XCOM data:
```
becquerel/tools/xcom.py:403: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
tables = pd.read_html(self._text, header=0, skiprows=[1, 2])
```

Address a FutureWarning from pandas

---

.pre-commit-config.yaml
CONTRIBUTING.md
becquerel/core/peakfinder.py
becquerel/core/plotting.py
becquerel/core/rebin.py
becquerel/core/spectrum.py
becquerel/tools/_nndc_dummy_text.py
examples/autocal.ipynb
examples/energycal.ipynb
examples/overview.ipynb
examples/rebinning.ipynb
tests/plotting_test.py

Title says it all. Also updates the contributor guidelines to reflect the need to run `pre-commit` and not just `black`.

Add codespell to pre-commit and fix spelling errors

---

becquerel/core/fitting.py
tests/fitting_test.py

`Fitter` already provides a `dict` of `best_values`, so this provides the corresponding `dict` of uncertainties.

Fitter.uncertainties dict

---

becquerel/core/calibration.py
becquerel/core/fitting.py
becquerel/core/plotting.py
becquerel/core/spectrum.py
becquerel/io/h5.py
becquerel/parsers/cnf.py
becquerel/parsers/spc.py
becquerel/parsers/spe.py
becquerel/tools/isotope.py
becquerel/tools/isotope_qty.py
becquerel/tools/materials.py
becquerel/tools/materials_compendium.py
becquerel/tools/nndc.py
becquerel/tools/xcom.py
examples/nndc_chart_of_nuclides.ipynb
pyproject.toml
tests/h5_tools_test.py
tests/materials_test.py
tests/wallet_cache_test.py

This PR enables the following [rulesets](https://docs.astral.sh/ruff/rules/) in [`ruff`](https://docs.astral.sh/ruff/):
- `SIM`: [flake8-simplify](https://pypi.org/project/flake8_simplify/) rules to simplify code
- `PL`: [pylint](https://pypi.org/project/pylint/) rules to "check[] for errors, enforce[] a coding standard, look[] for [code smells](https://martinfowler.com/bliki/CodeSmell.html), and [] make suggestions about how the code could be refactored"
I thought these made useful improvements and would be helpful for maintaining our code going forward.
This PR is a second take on #417 but without the experimental rules from [`ruff`'s `preview` mode](https://docs.astral.sh/ruff/preview/).

Enable pylint and other linting rules in ruff

---

becquerel/tools/xcom.py

The first energy in the list of user-specified energies seems to get discarded by the server. This is a kludge with a noisy warning to remind us to remove it when it gets fixed.
This kludge also works on the [XCOM website query](https://physics.nist.gov/PhysRefData/Xcom/html/xcom1.html) --- just add a "dummy" energy at the top of the "Additional energies in MeV" list.

Handle an apparent XCOM bug in energies list

---

becquerel/core/spectrum.py
tests/spectrum_test.py

I noticed with some Spectrum I/O stuff that comparing Spectrum objects wasn't working correctly:
This provides a custom `Spectrum.__eq__` method that checks only the relevant spectral data for equality, rather than attributes like filenames, which I guess is what happens when no `__eq__` method is provided.

add Spectrum.__eq__
